### ISSUE TITLE
add analytics

### ISSUE THREAD

**Issue by robphoenix** [robphoenix/diy-as-privilege#10]

**Comment by huxleyboon** [comment]
done (i think) hopefully it's enough?

**Comment by robphoenix** [comment]
um, what have you done? 🤔

**Comment by huxleyboon** [comment]
haha, I typed in a bunch of tag words into where I thought it should go?!

**Comment by robphoenix** [comment]
ha, ah yeah, cool thanks, this is something different :smile_cat: 
Google analytics or something, to see page views etc.
