### ISSUE TITLE
Menu change

### ISSUE THREAD

**Issue by huxleyboon** [robphoenix/diy-as-privilege#19]
Can we have the top menu just have - 

Manifesto / About / Publication

rather than

Home / Manifesto / About

?

And then this under a 'Publication' header below the artists bit - 

The Manifesto was originally published as a pamphlet by The Fringe and Underground Music Group at Goldsmiths as part of the ‘Spaces of Making’ project.

It was launched on Friday 11th May at an event at Lewisham Art House, with readings from myself, Charles Hayward, Marlo Delara & Sharon Gal.

Since then it has been published in the August 2018 issue of Maximum Rock n Roll magazine and Tate’s 2019 Playground Magazine.

Available in the Goldsmiths University Library Archive, Good Press Gallery in Glasgow, the Science and Media Museum in Bradford and Liz Harris/Grouper in the US.  

Translated into Greek by Zina Sarris for the Sounds Good Project with pending translations into French and Spanish. 

Please get in contact (my email - richardjamesphoenix@gmail.com) if you're interested in stocking or distributing the manifesto or translation it into another language. 

---

2nd version

200 copies riso-graph printed with teal ink on grey 180gsm matt paper Re-design in collaboration with Sean Roy Parker. 

Buy a copy

Download the PDF

![DAP_Edit1](https://user-images.githubusercontent.com/17753100/61965715-ca11e080-afc8-11e9-8c90-ddab2e025011.JPG)
![DAP_Edit3](https://user-images.githubusercontent.com/17753100/61965716-cb430d80-afc8-11e9-904f-8c04b109fffb.JPG)
 --- 

1st version

100 copies riso-graph printed with purple ink on grey 120gsm matt paper.  200 copies with various print colours and card colours.

![IMGP1597](https://user-images.githubusercontent.com/17753100/61965961-64722400-afc9-11e9-84d4-ac98c8437e01.JPG)
![IMGP1598](https://user-images.githubusercontent.com/17753100/61965962-650aba80-afc9-11e9-81dd-f1ccb2687266.JPG)

**Comment by robphoenix** [comment]
aye, I'll push these changes today :+1:

**Comment by robphoenix** [comment]
done ✨
