### ISSUE TITLE
spacing between text

### ISSUE THREAD

**Issue by huxleyboon** [robphoenix/diy-as-privilege#23]
could there bit a bit more of a gap between the text... I think in the "Why I wrote..." and "Publication" sections the text looks a bit dense.

**Comment by huxleyboon** [comment]
I mean the gaps between lines - can't remember what it's called! not the gaps between words/characters

**Comment by robphoenix** [comment]
😄  [line height](http://tachyons.io/docs/typography/line-height/)

Sure no worries.
